version: 2
updates:
  - package-ecosystem: github-actions #パッケージエコシステム
    directory: / #パッケージマニュフェストの配置先ディレクトリ
    schedule: 
      interval: daily #バージョンアップスケジュール
    ignore: #除外設定
      - dependency-name: actions/upload-artifact #除外する依存関係の名前
        versions: #除外対象のバージョン
          - 4.3.0
          - 4.3.1
      - dependency-name: 'actions/*' # アスタリスクは任意の文字列にマッチ
        update-types:
          - version-update:semver-major
