changelog:
  categories: #リリースノートのカテゴリ設定.
    - title: Enhancement
      labels:
        - enhancement
    -title: Bug Fixes
      labels:
        - bug
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot