name: Sequential Jbos
on: push
jobs:
  first:  #依存関係がないので最初に実行
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second: #firstの後に実行
    needs: [first] #needsキーへ依存するfirstジョブのIDを指定
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third: #secondsの後に実行
    runs-on: ubuntu-latest
    needs: [second] #needsキーへ依存するsecondジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Third job"